"""
데이터 수집 상태 정리
"""

print("\n" + "="*80)
print("📊 데이터 수집 상태 정리")
print("="*80 + "\n")

print("현재 상황:")
print("-" * 80)
print()

print("1️⃣ 완료된 수집 (우선주 70개)")
print("   날짜: 2025-11-24 02:27:18")
print("   종목: 70개 (우선주만)")
print("   기간: 2022-11-25 ~ 2025-11-24 (3년)")
print("   데이터: 46,298행")
print("   급락: 352회")
print("   성공 반등: 159회 (45.2%)")
print("   ✅ AI 학습 완료 (이 데이터로)")
print()

print("2️⃣ 중단된 수집 (전체 종목 2,784개)")
print("   시작: 2025-11-24 밤")
print("   목표: 2,784개 (일반주 + 우선주)")
print("   진행: 약 271개 수집 후 중단")
print("   원인: 재부팅으로 백그라운드 프로세스 종료")
print("   ❌ 미완료")
print()

print("\n" + "="*80)
print("❓ 혼란의 원인")
print("="*80 + "\n")

print("제가 '학습 완료'라고 한 것은:")
print("   → 우선주 70개 데이터로 학습 완료 ✅")
print()

print("하지만 말씀하신 '일반주 포함' 수집은:")
print("   → 시작했지만 중단됨 ❌")
print()

print("\n" + "="*80)
print("🔄 다음 단계 선택")
print("="*80 + "\n")

print("옵션 1: 기존 데이터로 계속 진행")
print("-" * 80)
print("   • 우선주 70개 데이터 사용")
print("   • 급락 352개 (충분함)")
print("   • AI 학습 이미 완료")
print("   • 최적화 결과:")
print("     - 익절/손절: +20% / -5%")
print("     - 물타기: 50% + 1회 (90.4% 수익률)")
print("   • 단점: 거래량 부족으로 실전 매매 제한적")
print()

print("옵션 2: 전체 종목 데이터 다시 수집")
print("-" * 80)
print("   • 2,784개 종목 수집 (30분~1시간)")
print("   • 예상 급락: 3,000개 이상")
print("   • AI 재학습 필요")
print("   • 장점: 더 많은 거래 기회, 높은 승률")
print("   • 단점: 시간 소요")
print()

print("옵션 3: 절충안 - 거래량 많은 종목만")
print("-" * 80)
print("   • 코스피/코스닥 상위 500개만 수집")
print("   • 거래량 1천만주 이상")
print("   • 시간: 10~15분")
print("   • 급락: 1,000개 이상 예상")
print("   • 균형잡힌 선택")
print()

print("\n" + "="*80)
print("💡 추천")
print("="*80 + "\n")

print("옵션 3 추천: 거래량 많은 상위 500개 종목")
print()
print("이유:")
print("   1. 시간 효율적 (10~15분)")
print("   2. 실전 매매 가능한 종목만")
print("   3. 충분한 급락 데이터")
print("   4. 우선주보다 훨씬 많은 기회")
print()

print("실행 명령:")
print("-" * 80)
print("cd /home/user1/auto_trading")
print("source learning/trading_bot/bin/activate")
print("python data_collection/crash_rebound_collector.py")
print()
print("(수집 시작 전 종목 수 제한 설정 가능)")
print()
